env:
  - BEHAT_PARAMS="formatter[name]=progress"

language: php

deploy:
  provider: heroku
  api_key:
    secure: LWWjSzCAleFgwUKsyxDcTANKZHM9NAhR2pUBxrsl1HR870HgkkoPZggiGvhJFJ1GELC5/vu7RtoRR9MC9P9Q2CQS10YHqUp1YyzYQDdR1TXwVq6Bh/86lq5LfDH8I1KfOs2km03YM8MFLO4rKtqd/mFtUXnnj5QcuRElh9PgISw=
  app: vast-anchorage-1004

php:
  - 5.3
script: ./bin/phpunit

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

