env:
  global:
    - secure: "1u21hjnmHjkghduUIJhhs76saljlkajdlfhGhgdJgfaVtgasfLLmNBnb87dad="

language: php

deploy:
  provider: heroku
  api_key: "YOUR API KEY"
  app: vast-anchorage-1004
php:
- 5.3

before_script:
- curl -s http://getcomposer.org/installer | php
- php composer.phar install

after_script:
  # Install the Heroku gem (or the Heroku toolbelt)
  - gem install heroku
  # Add your Heroku git repo:
  - git remote add git@heroku.com:vast-anchorage-1004.git
  # Add your Heroku API key:
  - export HEROKU_API_KEY=LWWjSzCAleFgwUKsyxDcTANKZHM9NAhR2pUBxrsl1HR870HgkkoPZggiGvhJFJ1GELC5/vu7RtoRR9MC9P9Q2CQS10YHqUp1YyzYQDdR1TXwVq6Bh/86lq5LfDH8I1KfOs2km03YM8MFLO4rKtqd/mFtUXnnj5QcuRElh9PgISw=
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear your current Heroku SSH keys:
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  # Push to Heroku!
  - yes | git push heroku master
